Repository How-about-over-there/server, pull requests merged in 2025-01, with the labels that each got.

#19 [Initialize] 유저 초기 API 설계
  user/build.gradle
  user/src/main/java/com/haot/user/application/req/AdminUserUpdateRequest.java
  user/src/main/java/com/haot/user/application/req/UserLoginValidationRequest.java
  user/src/main/java/com/haot/user/application/req/UserUpdateMeRequest.java
  user/src/main/java/com/haot/user/application/res/AdminUserGetResponse.java
  user/src/main/java/com/haot/user/application/res/UserGetMeResponse.java
  user/src/main/java/com/haot/user/application/res/UserLoginValidationResponse.java
  user/src/main/java/com/haot/user/application/res/UserValidationResponse.java
  user/src/main/java/com/haot/user/common/response/ApiResponse.java
  user/src/main/java/com/haot/user/domain/model/User.java
  user/src/main/java/com/haot/user/domain/model/enums/Gender.java
  user/src/main/java/com/haot/user/domain/model/enums/Role.java
  user/src/main/java/com/haot/user/presentation/controller/AdminUserController.java
  user/src/main/java/com/haot/user/presentation/controller/UserController.java
  user/src/main/resources/application.properties
  user/src/main/resources/application.yml
  user/src/test/java/com/haot/user/presentation/controller/AdminUserControllerTest.java
  user/src/test/java/com/haot/user/presentation/controller/UserControllerTest.java
Labels: feature, Initialize

#20 [Initialize] Lodge: 서비스 초기 API 설계
  lodge/build.gradle
  lodge/src/main/java/com/haot/lodge/LodgeApplication.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeDateResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeRuleResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/lodgeImageResponse.java
  lodge/src/main/java/com/haot/lodge/common/response/ApiResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeCreateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeDateUpdateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeUpdateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeCreateResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeDateReadResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeReadAllResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeReadOneResponse.java
  lodge/src/main/resources/application.yml
Labels: feature, Initialize

#26 [Feat] User: 로그인 정보 검증 API 구현
  user/build.gradle
  user/src/main/java/com/haot/user/application/dto/req/AdminUserUpdateRequest.java
  user/src/main/java/com/haot/user/application/dto/req/UserLoginValidationRequest.java
  user/src/main/java/com/haot/user/application/dto/req/UserUpdateMeRequest.java
  user/src/main/java/com/haot/user/application/dto/res/AdminUserGetResponse.java
  user/src/main/java/com/haot/user/application/dto/res/UserGetMeResponse.java
  user/src/main/java/com/haot/user/application/dto/res/UserLoginValidationResponse.java
  user/src/main/java/com/haot/user/application/dto/res/UserValidationResponse.java
  user/src/main/java/com/haot/user/application/res/UserLoginValidationResponse.java
  user/src/main/java/com/haot/user/application/service/UserValidationService.java
  user/src/main/java/com/haot/user/application/service/UserValidationServiceImpl.java
  user/src/main/java/com/haot/user/common/exception/ApplicationException.java
  user/src/main/java/com/haot/user/common/exception/ErrorCode.java
  user/src/main/java/com/haot/user/common/exception/GlobalExceptionHandler.java
  user/src/main/java/com/haot/user/common/response/ErrorResponse.java
  user/src/main/java/com/haot/user/common/util/Argon2PasswordEncoder.java
  user/src/main/java/com/haot/user/infrastructure/repository/UserRepository.java
  user/src/main/java/com/haot/user/presentation/controller/AdminUserController.java
  user/src/main/java/com/haot/user/presentation/controller/UserController.java
Labels: feature

#25 [Feat] Reservation: 예약 날짜 테이블 설계 및 예약 상태
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationCreateRequest.java
  reservation/src/main/java/com/haot/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/haot/reservation/domain/model/ReservationDate.java
  reservation/src/main/java/com/haot/reservation/domain/model/ReservationStatus.java
Labels: feature, Initialize

#27 [Initialize] Payment: 결제 API 초기 설계 구현
  payment/build.gradle
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentCancelRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentCreateRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentUpdateRequest.java
  payment/src/main/java/com/haot/payment/application/dto/response/PaymentResponse.java
  payment/src/main/java/com/haot/payment/common/response/ApiResponse.java
  payment/src/main/java/com/haot/payment/presentation/controller/AdminPaymentController.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
  payment/src/main/resources/application.properties
  payment/src/main/resources/application.yml
  payment/src/test/java/com/haot/payment/presentation/controller/AdminPaymentControllerTest.java
  payment/src/test/java/com/haot/payment/presentation/controller/PaymentControllerTest.java
Labels: Initialize

#30 [Initialize] 초기 쿠폰 API 설계 구현
  coupon/build.gradle
  coupon/src/main/java/com/haot/coupon/CouponApplication.java
  coupon/src/main/java/com/haot/coupon/application/dto/request/coupons/CouponCreateRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/request/coupons/CouponCustomerCreateRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/request/coupons/CouponSearchRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/request/events/EventCreateRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/request/events/EventModifyRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/request/events/EventSearchRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/coupons/CouponCreateResponse.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/coupons/CouponHistoryResponse.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/coupons/CouponReadMeResponse.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/coupons/CouponSearchResponse.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/coupons/ReservationVerifyResponse.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/events/EventCreateResponse.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/events/EventSearchResponse.java
  coupon/src/main/java/com/haot/coupon/common/response/ApiResponse.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/CouponStatus.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/CouponType.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/DiscountPolicy.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/EventStatus.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/ReservationCouponStatus.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminCouponController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminEventController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/EventController.java
  coupon/src/main/resources/application.properties
  coupon/src/main/resources/application.yml
Labels: Initialize

#31 [Feat] User: 아이디를 통한 유저 존재성 검증 API 구현
  user/src/main/java/com/haot/user/application/service/UserValidationService.java
  user/src/main/java/com/haot/user/application/service/UserValidationServiceImpl.java
  user/src/main/java/com/haot/user/presentation/controller/UserController.java
Labels: feature

#33 [Initialize] Point: 포인트 API 초기 설계 구현
  point/build.gradle
  point/src/main/java/com/haot/point/application/dto/request/PointCreateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/PointHistoryCreateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/PointHistoryUpdateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/PointStatusRequest.java
  point/src/main/java/com/haot/point/application/dto/request/PointTransactionRequest.java
  point/src/main/java/com/haot/point/application/dto/request/PointUpdateRequest.java
  point/src/main/java/com/haot/point/application/dto/response/PointAllResponse.java
  point/src/main/java/com/haot/point/application/dto/response/PointHistoryResponse.java
  point/src/main/java/com/haot/point/application/dto/response/PointResponse.java
  point/src/main/java/com/haot/point/common/response/ApiResponse.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointController.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointHistoryController.java
  point/src/main/java/com/haot/point/presentation/controller/PointController.java
  point/src/main/java/com/haot/point/presentation/controller/PointHistoryController.java
  point/src/main/resources/application.properties
  point/src/main/resources/application.yml
  point/src/test/java/com/haot/point/presentation/controller/AdminPointControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/AdminPointHistoryControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/PointControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/PointHistoryControllerTest.java
Labels: Initialize

#32 [Feat] User: User Create API 구현
  user/src/main/java/com/haot/user/application/dto/req/UserCreateRequest.java
  user/src/main/java/com/haot/user/application/dto/res/UserCreateResponse.java
  user/src/main/java/com/haot/user/application/dto/res/UserLoginValidationResponse.java
  user/src/main/java/com/haot/user/application/dto/res/UserValidationResponse.java
  user/src/main/java/com/haot/user/application/service/UserCRUDService.java
  user/src/main/java/com/haot/user/application/service/UserCRUDServiceImpl.java
  user/src/main/java/com/haot/user/application/service/UserValidationServiceImpl.java
  user/src/main/java/com/haot/user/domain/model/User.java
  user/src/main/java/com/haot/user/presentation/controller/UserController.java
Labels: feature

#36 Feature/coupon/domain/#15
  coupon/src/main/java/com/haot/coupon/application/dto/request/coupons/CouponCreateRequest.java
  coupon/src/main/java/com/haot/coupon/common/exceptions/CustomCouponException.java
  coupon/src/main/java/com/haot/coupon/common/exceptions/handler/CustomCouponExceptionHandler.java
  coupon/src/main/java/com/haot/coupon/common/exceptions/handler/GlobalExceptionHandler.java
  coupon/src/main/java/com/haot/coupon/common/exceptions/handler/ValidExceptionHandler.java
  coupon/src/main/java/com/haot/coupon/common/response/ApiResponse.java
  coupon/src/main/java/com/haot/coupon/common/response/ResCodeIfs.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/domain/model/Coupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/CouponEvent.java
  coupon/src/main/java/com/haot/coupon/domain/model/ReservationCoupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/UserCoupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/vo/CouponDiscountRate.java
  coupon/src/main/java/com/haot/coupon/infrastructure/config/ValidationMessageConfig.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponEventRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/ReservationCouponRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/UserCouponRepository.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminCouponController.java
  coupon/src/main/resources/application.yml
  coupon/src/main/resources/validation-messages-ko.properties
Labels: feature

#40 [Feat] Payment: 결제 도메인 설계 구현
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentUpdateRequest.java
  payment/src/main/java/com/haot/payment/domain/enums/PaymentMethod.java
  payment/src/main/java/com/haot/payment/domain/enums/PaymentStatus.java
  payment/src/main/java/com/haot/payment/domain/model/Payment.java
  payment/src/main/java/com/haot/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/resources/application.yml
Labels: feature

#41 [Feat] Lodge: 숙소 정보 생성 API
  lodge/src/main/java/com/haot/lodge/application/response/LodgeResponse.java
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeBasicService.java
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeImageService.java
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeRuleService.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/common/config/ValidationMessageConfig.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/common/exception/GlobalControllerAdvice.java
  lodge/src/main/java/com/haot/lodge/common/exception/LodgeException.java
  lodge/src/main/java/com/haot/lodge/common/response/ApiResponse.java
  lodge/src/main/java/com/haot/lodge/domain/model/Lodge.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeDate.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeImage.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeRule.java
  lodge/src/main/java/com/haot/lodge/domain/model/enums/ReservationStatus.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeDateRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeImageRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeRuleRepository.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeCreateRequest.java
  lodge/src/main/resources/validation-messages-ko.properties
Labels: feature

#46 [Feat] Lodge: 숙소 날짜 상태 변경 API
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeDate.java
  lodge/src/main/java/com/haot/lodge/domain/model/enums/ReservationStatus.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeDateUpdateStatusRequest.java
Labels: feature

#48 [Feat] Lodge: 숙소 단건 조회 API
  lodge/src/main/java/com/haot/lodge/application/response/LodgeRuleResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/lodgeImageResponse.java
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeBasicService.java
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeRuleService.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/domain/model/Lodge.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeRuleRepository.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeReadAllResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeReadOneResponse.java
Labels: feature

#45 [Feature] 쿠폰 생성 API 추가#38
  coupon/build.gradle
  coupon/src/main/java/com/haot/coupon/application/dto/request/coupons/CouponCreateRequest.java
  coupon/src/main/java/com/haot/coupon/application/mapper/CouponMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/AdminCouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/AdminCouponServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/domain/model/Coupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/CouponType.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/DiscountPolicy.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/ReservationCouponStatus.java
  coupon/src/main/java/com/haot/coupon/domain/model/vo/CouponDiscountRate.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminCouponController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
  coupon/src/main/resources/validation-messages-ko.properties
Labels: feature

#55 [Feat] Lodge: BaseEntity
  lodge/src/main/java/com/haot/lodge/application/response/LodgeImageResponse.java
  lodge/src/main/java/com/haot/lodge/domain/config/AuditorAwareImpl.java
  lodge/src/main/java/com/haot/lodge/domain/config/JpaAuditConfig.java
  lodge/src/main/java/com/haot/lodge/domain/model/BaseEntity.java
  lodge/src/main/java/com/haot/lodge/domain/model/Lodge.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeDate.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeImage.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeRule.java
Labels: feature

#49 [feat] 이벤트 생성 API 기능 구현
  coupon/src/main/java/com/haot/coupon/application/dto/request/coupons/CouponCreateRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/request/events/EventCreateRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/response/events/EventCreateResponse.java
  coupon/src/main/java/com/haot/coupon/application/mapper/EventMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/AdminCouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/AdminEventService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/AdminEventServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/ApiResponse.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/SuccessCode.java
  coupon/src/main/java/com/haot/coupon/domain/model/Coupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/CouponEvent.java
  coupon/src/main/java/com/haot/coupon/domain/model/ReservationCoupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/UserCoupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/EventStatus.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponEventRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponRepository.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminCouponController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminEventController.java
Labels: feature

#58 [Feat] 숙소 날짜 목록 조회 API
  lodge/build.gradle
  lodge/src/main/java/com/haot/lodge/application/response/LodgeDateResponse.java
  lodge/src/main/java/com/haot/lodge/application/service/Impl/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/domain/config/QueryDslConfig.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeDateCustomRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeDateRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/impl/LodgeDateCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
Labels: feature

#42 [Feat] Point: 포인트 도메인 설계 구현
  point/src/main/java/com/haot/point/domain/enums/PointStatus.java
  point/src/main/java/com/haot/point/domain/enums/PointType.java
  point/src/main/java/com/haot/point/domain/model/Point.java
  point/src/main/java/com/haot/point/domain/model/PointHistory.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepository.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointRepository.java
  point/src/main/resources/application.yml
Labels: feature

#57 [Feat] Auth: 로그인 API 구현
  auth/src/main/java/com/haot/auth/application/dto/req/AuthLoginRequest.java
  auth/src/main/java/com/haot/auth/application/dto/res/AuthLoginResponse.java
  auth/src/main/java/com/haot/auth/application/feign/port/UserClientPort.java
  auth/src/main/java/com/haot/auth/application/service/AuthService.java
  auth/src/main/java/com/haot/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/haot/auth/common/util/JwtUtils.java
  auth/src/main/java/com/haot/auth/infrastructure/feign/adapter/UserClientAdapter.java
  auth/src/main/java/com/haot/auth/infrastructure/feign/client/UserClient.java
  auth/src/main/java/com/haot/auth/infrastructure/feign/dto/FeignUserLoginValidationRequest.java
  auth/src/main/java/com/haot/auth/infrastructure/feign/dto/FeignUserLoginValidationResponse.java
  auth/src/main/java/com/haot/auth/presentation/controller/AuthController.java
  auth/src/main/resources/application.yml
  user/src/main/java/com/haot/user/application/service/UserCRUDServiceImpl.java
  user/src/main/java/com/haot/user/common/exception/ErrorCode.java
  user/src/main/java/com/haot/user/infrastructure/repository/UserRepository.java
Labels: feature

#60 [Feat] Payment: 결제 생성 및 확인 API 구현
  payment/src/main/java/com/haot/payment/application/dto/response/PaymentResponse.java
  payment/src/main/java/com/haot/payment/application/service/PaymentService.java
  payment/src/main/java/com/haot/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/haot/payment/common/exception/CustomPaymentException.java
  payment/src/main/java/com/haot/payment/common/exception/enums/ErrorCode.java
  payment/src/main/java/com/haot/payment/common/exception/handler/CustomPaymentExceptionHandler.java
  payment/src/main/java/com/haot/payment/common/exception/handler/GlobalExceptionHandler.java
  payment/src/main/java/com/haot/payment/common/exception/handler/ValidExceptionHandler.java
  payment/src/main/java/com/haot/payment/common/response/ApiResponse.java
  payment/src/main/java/com/haot/payment/common/response/ResCodeIfs.java
  payment/src/main/java/com/haot/payment/domain/config/AuditorAwareImpl.java
  payment/src/main/java/com/haot/payment/domain/config/JpaAuditConfig.java
  payment/src/main/java/com/haot/payment/domain/enums/PaymentMethod.java
  payment/src/main/java/com/haot/payment/domain/enums/PaymentStatus.java
  payment/src/main/java/com/haot/payment/domain/model/BaseEntity.java
  payment/src/main/java/com/haot/payment/domain/model/Payment.java
  payment/src/main/java/com/haot/payment/infrastructure/client/PortOneService.java
  payment/src/main/java/com/haot/payment/infrastructure/client/dto/PortOneResponse.java
  payment/src/main/java/com/haot/payment/infrastructure/config/ValidationMessageConfig.java
  payment/src/main/java/com/haot/payment/presentation/controller/AdminPaymentController.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
  payment/src/main/resources/application.yml
  payment/src/main/resources/static/payment.html
  payment/src/main/resources/validation-messages-ko.properties
Labels: feature

#63 [Feat] Point: 포인트 생성 API 구현
  point/src/main/java/com/haot/point/application/dto/response/PointResponse.java
  point/src/main/java/com/haot/point/application/service/PointService.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/common/exception/CustomPointException.java
  point/src/main/java/com/haot/point/common/exception/enums/ErrorCode.java
  point/src/main/java/com/haot/point/common/exception/handler/CustomPointExceptionHandler.java
  point/src/main/java/com/haot/point/common/exception/handler/GlobalExceptionHandler.java
  point/src/main/java/com/haot/point/common/exception/handler/ValidExceptionHandler.java
  point/src/main/java/com/haot/point/common/response/ApiResponse.java
  point/src/main/java/com/haot/point/common/response/ResCodeIfs.java
  point/src/main/java/com/haot/point/domain/config/AuditorAwareImpl.java
  point/src/main/java/com/haot/point/domain/config/JpaAuditConfig.java
  point/src/main/java/com/haot/point/domain/model/BaseEntity.java
  point/src/main/java/com/haot/point/domain/model/Point.java
  point/src/main/java/com/haot/point/domain/model/PointHistory.java
  point/src/main/java/com/haot/point/infrastructure/config/ValidationMessageConfig.java
  point/src/main/java/com/haot/point/presentation/controller/PointController.java
  point/src/main/resources/validation-messages-ko.properties
Labels: feature

#65 [Feat] Lodge: 숙소 정보 수정 API
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeServiceImpl.java
  lodge/src/main/java/com/haot/lodge/domain/model/Lodge.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeUpdateRequest.java
Labels: feature

#64 [Feat] Gateway: Gateway 설정 및 인증 필터 구현
  auth/src/main/resources/application.yml
  gateway/build.gradle
  gateway/src/main/java/com/haot/gateway/client/UserWebClient.java
  gateway/src/main/java/com/haot/gateway/config/WebClientConfig.java
  gateway/src/main/java/com/haot/gateway/data/Role.java
  gateway/src/main/java/com/haot/gateway/data/UserValidationResponse.java
  gateway/src/main/java/com/haot/gateway/exception/ErrorCode.java
  gateway/src/main/java/com/haot/gateway/exception/GatewayException.java
  gateway/src/main/java/com/haot/gateway/exception/GlobalExceptionHandler.java
  gateway/src/main/java/com/haot/gateway/filter/JwtAuthenticationFilter.java
  gateway/src/main/java/com/haot/gateway/util/JwtUtils.java
  gateway/src/main/resources/application.properties
  gateway/src/main/resources/application.yml
Labels: feature

#67 [Feat] Point: 포인트 단건 조회 API 구현
  point/src/main/java/com/haot/point/application/service/PointService.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointRepository.java
  point/src/main/java/com/haot/point/presentation/controller/PointController.java
Labels: feature

#71 [Feat] Payment: 본인 결제 단건 조회 API 구현
  payment/src/main/java/com/haot/payment/application/service/PaymentService.java
  payment/src/main/java/com/haot/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/haot/payment/infrastructure/client/PortOneService.java
  payment/src/main/java/com/haot/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
Labels: feature

#74 쿠폰 발급 API 기능 구현 #56
  coupon/build.gradle
  coupon/src/main/java/com/haot/coupon/application/kafka/CouponErrorConsumer.java
  coupon/src/main/java/com/haot/coupon/application/kafka/CouponErrorProducer.java
  coupon/src/main/java/com/haot/coupon/application/mapper/UserCouponMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/CouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/AdminEventServiceImpl.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/CouponServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/ApiResponse.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/SuccessCode.java
  coupon/src/main/java/com/haot/coupon/domain/model/Coupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/CouponEvent.java
  coupon/src/main/java/com/haot/coupon/domain/model/UserCoupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/EventStatus.java
  coupon/src/main/java/com/haot/coupon/infrastructure/config/KafkaConfig.java
  coupon/src/main/java/com/haot/coupon/infrastructure/kafka/CouponErrorFrontConsumer.java
  coupon/src/main/java/com/haot/coupon/infrastructure/kafka/CouponErrorFrontProducer.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponEventRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/UserCouponRepository.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
  coupon/src/main/resources/application.yml
  docker-compose.yml
Labels: feature

#77 [feat]이벤트 단건 조회 API
  coupon/src/main/java/com/haot/coupon/application/mapper/EventMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/EventService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/EventServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/SuccessCode.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/EventController.java
Labels: feature

#78 [feat] 쿠폰 단건 조회 API
  coupon/src/main/java/com/haot/coupon/application/dto/response/coupons/CouponSearchResponse.java
  coupon/src/main/java/com/haot/coupon/application/mapper/CouponMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/CouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/CouponServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/SuccessCode.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminCouponController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
Labels: feature

#82 [Feat] Lodge: 숙소 목록 조회 및 검색 API
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeServiceImpl.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeCustomRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/impl/LodgeCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/domain/repository/impl/LodgeDateCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/domain/utils/QuerydslSortUtils.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeReadAllResponse.java
Labels: feature, refactor

#84 [Feat] Review: 리뷰 생성 API
  .gitmodules
  review/.gitattributes
  review/.gitignore
  review/build.gradle
  review/gradle/wrapper/gradle-wrapper.jar
  review/gradle/wrapper/gradle-wrapper.properties
  review/gradlew
  review/gradlew.bat
  review/settings.gradle
  review/src/main/java/com/haot/review/ReviewApplication.java
  review/src/main/java/com/haot/review/application/dtos/req/ReviewCreateRequest.java
  review/src/main/java/com/haot/review/application/dtos/res/ReviewGetResponse.java
  review/src/main/java/com/haot/review/application/service/MockS3Service.java
  review/src/main/java/com/haot/review/application/service/ReviewService.java
  review/src/main/java/com/haot/review/common/response/ApiResponse.java
  review/src/main/java/com/haot/review/domain/model/Review.java
  review/src/main/java/com/haot/review/domain/model/ReviewImage.java
  review/src/main/java/com/haot/review/domain/repository/ReviewImageRepository.java
  review/src/main/java/com/haot/review/domain/repository/ReviewRepository.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewController.java
  review/src/main/java/com/haot/review/submodule/auditor/AuditorAwareImpl.java
  review/src/main/java/com/haot/review/submodule/auditor/BaseEntity.java
  review/src/main/java/com/haot/review/submodule/auditor/JpaConfig.java
  review/src/main/java/com/haot/review/submodule/role/Role.java
  review/src/main/java/com/haot/review/submodule/role/RoleAspect.java
  review/src/main/java/com/haot/review/submodule/role/RoleCheck.java
  review/src/main/resources/application.yml
  review/src/main/resources/validation-messages-ko.properties
  review/src/test/java/com/haot/review/ReviewApplicationTests.java
Labels: feature

#89 [Feat] Lodge: 숙소 날짜 정보 수정 API
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeDateFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeDateServiceImpl.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeDate.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeDateRepository.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeDateUpdateRequest.java
Labels: feature

#94 [Feat] 리뷰 단건 조회 API 구현
  review/src/main/java/com/haot/review/application/service/ReviewService.java
  review/src/main/java/com/haot/review/common/exceptions/CustomReviewException.java
  review/src/main/java/com/haot/review/common/exceptions/handler/CustomReviewExceptionHandler.java
  review/src/main/java/com/haot/review/common/response/ApiResponse.java
  review/src/main/java/com/haot/review/common/response/ResCodeIfs.java
  review/src/main/java/com/haot/review/common/response/enums/ErrorCode.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewController.java
Labels: feature

#93 [Feat] Payment: 결제 취소 요청 API 구현
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentCancelRequest.java
  payment/src/main/java/com/haot/payment/application/service/PaymentService.java
  payment/src/main/java/com/haot/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/haot/payment/domain/enums/PaymentStatus.java
  payment/src/main/java/com/haot/payment/domain/model/Payment.java
  payment/src/main/java/com/haot/payment/infrastructure/client/PortOneService.java
  payment/src/main/java/com/haot/payment/infrastructure/client/dto/request/PortOneCancelRequest.java
  payment/src/main/java/com/haot/payment/infrastructure/client/dto/response/PortOneCancelResponse.java
  payment/src/main/java/com/haot/payment/infrastructure/client/dto/response/PortOneResponse.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
Labels: feature

#86 [Feat] Point: 포인트 사용 API 구현
  point/src/main/java/com/haot/point/application/dto/request/PointStatusRequest.java
  point/src/main/java/com/haot/point/application/dto/request/PointTransactionRequest.java
  point/src/main/java/com/haot/point/application/dto/response/PointAllResponse.java
  point/src/main/java/com/haot/point/application/service/PointService.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/common/exception/enums/ErrorCode.java
  point/src/main/java/com/haot/point/domain/enums/PointStatus.java
  point/src/main/java/com/haot/point/domain/enums/PointType.java
  point/src/main/java/com/haot/point/domain/model/Point.java
  point/src/main/java/com/haot/point/domain/model/PointHistory.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepository.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointRepository.java
  point/src/main/java/com/haot/point/presentation/controller/PointController.java
Labels: feature

#102 [Feat] Lodge: API 접근 권한 설정
  gateway/src/main/resources/application.yml
  lodge/build.gradle
  lodge/src/main/java/com/haot/lodge/LodgeApplication.java
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeDateFacade.java
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/domain/config/AuditorAwareImpl.java
  lodge/src/main/java/com/haot/lodge/domain/config/JpaAuditConfig.java
  lodge/src/main/java/com/haot/lodge/domain/model/BaseEntity.java
  lodge/src/main/java/com/haot/lodge/domain/model/Lodge.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeDate.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeImage.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeRule.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
Labels: feature

#109 쿠폰 상태 변경 API 구현
  coupon/src/main/java/com/haot/coupon/application/dto/feign/request/FeignConfirmReservationRequest.java
  coupon/src/main/java/com/haot/coupon/application/dto/feign/response/ReservationVerifyResponse.java
  coupon/src/main/java/com/haot/coupon/application/mapper/ReservationCouponMapper.java
  coupon/src/main/java/com/haot/coupon/application/mapper/UserCouponMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/CouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/CouponServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/SuccessCode.java
  coupon/src/main/java/com/haot/coupon/domain/model/ReservationCoupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/UserCoupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/ReservationCouponStatus.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/ReservationCouponRepository.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
Labels: feature

#110 [Feat] Lodge: 숙소 삭제 API
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeImageService.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeRuleService.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeDateServiceImpl.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeImageServiceImpl.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeRuleServiceImpl.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeServiceImpl.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeRepository.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
Labels: feature

#108 [Feat] Payment: 본인 결제 전체 조회 및 검색 API 구현
  payment/build.gradle
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentSearchRequest.java
  payment/src/main/java/com/haot/payment/application/service/PaymentService.java
  payment/src/main/java/com/haot/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/haot/payment/infrastructure/config/QueryDslConfig.java
  payment/src/main/java/com/haot/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/java/com/haot/payment/infrastructure/repository/PaymentRepositoryCustom.java
  payment/src/main/java/com/haot/payment/infrastructure/repository/PaymentRepositoryCustomImpl.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
Labels: feature

#113 [Feat] Review: 리뷰 검색 API 구현
  review/build.gradle
  review/src/main/java/com/haot/review/application/dtos/req/ReviewSearchRequest.java
  review/src/main/java/com/haot/review/application/service/ReviewService.java
  review/src/main/java/com/haot/review/domain/repository/ReviewRepository.java
  review/src/main/java/com/haot/review/infrastructure/configuration/QueryDslConfig.java
  review/src/main/java/com/haot/review/infrastructure/repository/ReviewRepositoryCustom.java
  review/src/main/java/com/haot/review/infrastructure/repository/ReviewRepositoryCustomImpl.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewController.java
Labels: feature

#114 [Feat] Point: 포인트 상태 변경 API 구현
  point/src/main/java/com/haot/point/application/dto/request/PointStatusRequest.java
  point/src/main/java/com/haot/point/application/service/PointHistoryService.java
  point/src/main/java/com/haot/point/application/service/PointHistoryServiceImpl.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/common/exception/enums/ErrorCode.java
  point/src/main/java/com/haot/point/domain/enums/PointStatus.java
  point/src/main/java/com/haot/point/domain/enums/PointType.java
  point/src/main/java/com/haot/point/domain/model/PointHistory.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepository.java
  point/src/main/java/com/haot/point/presentation/controller/PointHistoryController.java
Labels: feature

#118 [Feat] Review: 리뷰 권한 체크, serviceImpl 생성
  review/src/main/java/com/haot/review/application/service/ReviewService.java
  review/src/main/java/com/haot/review/application/service/ReviewServiceImpl.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewController.java
Labels: feature

#120 [feat] 내 쿠폰함 조회 API 구현
  coupon/build.gradle
  coupon/src/main/java/com/haot/coupon/application/dto/response/coupons/CouponReadMeResponse.java
  coupon/src/main/java/com/haot/coupon/application/mapper/UserCouponMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/CouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/CouponServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/SuccessCode.java
  coupon/src/main/java/com/haot/coupon/domain/utils/QueryDslSortUtils.java
  coupon/src/main/java/com/haot/coupon/infrastructure/config/QueryDslConfig.java
  coupon/src/main/java/com/haot/coupon/infrastructure/config/QueryDslPageableConfig.java
  coupon/src/main/java/com/haot/coupon/infrastructure/config/QueryDslPageableResolver.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/UserCouponCustomRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/UserCouponRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/impl/UserCouponCustomRepositoryImpl.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
Labels: feature

#121 [Feat] Lodge: 숙소 아이디 유효성 확인 API
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeServiceImpl.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeRepository.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
Labels: feature

#127 이벤트 조회 API 구현
  coupon/src/main/java/com/haot/coupon/application/dto/request/events/EventSearchRequest.java
  coupon/src/main/java/com/haot/coupon/application/mapper/EventMapper.java
  coupon/src/main/java/com/haot/coupon/application/mapper/UserCouponMapper.java
  coupon/src/main/java/com/haot/coupon/application/service/EventService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/EventServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponEventCustomRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponEventRepository.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/impl/CouponEventCustomRepositoryImpl.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminCouponController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/AdminEventController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/EventController.java
Labels: feature

#132 [Feat] Reservation: 예약 수정 API 구현 #130
  reservation/src/main/java/com/haot/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/payment/PaymentResponse.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/ReservationController.java
Labels: feature

#131 [Feat] Lodge: 숙소 날짜 추가 생성 API
  .gitmodules
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeDateFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeDateServiceImpl.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeDateCustomRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/impl/LodgeDateCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeDateAddRequest.java
Labels: feature

#136 [Feat] Reservation: 예약 단건 조회 API 구현
  reservation/src/main/java/com/haot/reservation/application/dtos/res/ReservationGetResponse.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/haot/reservation/common/exceptions/CustomReservationException.java
  reservation/src/main/java/com/haot/reservation/common/exceptions/handler/GlobalExceptionHandler.java
  reservation/src/main/java/com/haot/reservation/common/response/ApiResponse.java
  reservation/src/main/java/com/haot/reservation/common/response/enums/ErrorCode.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/ReservationController.java
Labels: feature

#139 쿠폰 rollback API 구현
  coupon/src/main/java/com/haot/coupon/application/service/CouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/CouponServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/SuccessCode.java
  coupon/src/main/java/com/haot/coupon/domain/model/enums/ReservationCouponStatus.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/ReservationCouponRepository.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
Labels: feature

#140 [Fix] Reservation: 롤백 로직 #137
  reservation/build.gradle
  reservation/src/main/java/com/haot/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/haot/reservation/infrastructure/client/CouponClient.java
Labels: bug, fix

#141 [fix] 쿠폰 발급 API 수정
  coupon/build.gradle
  coupon/src/main/java/com/haot/coupon/application/cache/RedisRepository.java
  coupon/src/main/java/com/haot/coupon/application/kafka/CouponIssueConsumer.java
  coupon/src/main/java/com/haot/coupon/application/kafka/CouponIssueProducer.java
  coupon/src/main/java/com/haot/coupon/application/service/CouponService.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/AdminEventServiceImpl.java
  coupon/src/main/java/com/haot/coupon/application/service/impl/CouponServiceImpl.java
  coupon/src/main/java/com/haot/coupon/common/response/enums/ErrorCode.java
  coupon/src/main/java/com/haot/coupon/domain/model/Coupon.java
  coupon/src/main/java/com/haot/coupon/domain/model/CouponEvent.java
  coupon/src/main/java/com/haot/coupon/infrastructure/cache/RedisRepositoryImpl.java
  coupon/src/main/java/com/haot/coupon/infrastructure/config/RedisConfig.java
  coupon/src/main/java/com/haot/coupon/infrastructure/kafka/CouponIssuedConsumer.java
  coupon/src/main/java/com/haot/coupon/infrastructure/kafka/CouponIssuedProducer.java
  coupon/src/main/java/com/haot/coupon/infrastructure/repository/CouponEventRepository.java
  coupon/src/main/java/com/haot/coupon/presentation/controller/CouponController.java
  coupon/src/main/resources/application.yml
  docker-compose.yml
Labels: bug, fix

#145 [Fix] Reservation: exception 수정
  reservation/src/main/java/com/haot/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/haot/reservation/common/exceptions/FeignExceptionUtils.java
  reservation/src/main/java/com/haot/reservation/common/response/enums/ErrorCode.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/ReservationController.java
Labels: fix

#146 [Feat] Lodge: 숙소 이미지 S3 업로드 기능
  lodge/build.gradle
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeImageServiceImpl.java
  lodge/src/main/java/com/haot/lodge/common/config/S3Config.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/common/exception/GlobalControllerAdvice.java
  lodge/src/main/java/com/haot/lodge/common/utils/S3Service.java
  lodge/src/main/resources/application.yml
Labels: feature

#150 [Refactor] Payment: 권한 및 userId 검증 추가
  payment/src/main/java/com/haot/payment/application/service/PaymentService.java
  payment/src/main/java/com/haot/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
Labels: feature, refactor

#152 [Feat] Reservation: 예약 취소 API 구현
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationCancelRequest.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/haot/reservation/common/response/enums/ErrorCode.java
  reservation/src/main/java/com/haot/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/haot/reservation/infrastructure/client/PaymentClient.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/payment/PaymentCancelRequest.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/ReservationController.java
Labels: feature

#154 [Feat] Point: 본인 포인트 내역 단건 조회 구현
  point/src/main/java/com/haot/point/application/dto/response/PointHistoryResponse.java
  point/src/main/java/com/haot/point/application/service/PointHistoryService.java
  point/src/main/java/com/haot/point/application/service/PointHistoryServiceImpl.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/common/exception/enums/ErrorCode.java
  point/src/main/java/com/haot/point/presentation/controller/PointHistoryController.java
Labels: feature

#156 [Feat] Point: 본인 포인트 내역 전체 조회 및 검색 구현
  point/build.gradle
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistoryCreateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistoryUpdateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/point/PointCreateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/point/PointStatusRequest.java
  point/src/main/java/com/haot/point/application/dto/request/point/PointUpdateRequest.java
  point/src/main/java/com/haot/point/application/service/PointHistoryService.java
  point/src/main/java/com/haot/point/application/service/PointHistoryServiceImpl.java
  point/src/main/java/com/haot/point/application/service/PointService.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/infrastructure/config/QueryDslConfig.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepository.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepositoryCustom.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepositoryCustomImpl.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointController.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointHistoryController.java
  point/src/main/java/com/haot/point/presentation/controller/PointController.java
  point/src/main/java/com/haot/point/presentation/controller/PointHistoryController.java
  point/src/test/java/com/haot/point/presentation/controller/AdminPointControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/AdminPointHistoryControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/PointControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/PointHistoryControllerTest.java
Labels: feature

#160 [Fix] Payment: 결제 페이지 Token 문제 해결
  gateway/src/main/java/com/haot/gateway/filter/JwtAuthenticationFilter.java
  gateway/src/main/resources/application.yml
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
  payment/src/main/resources/static/payment.html
Labels: fix

#161 [Fix] Lodge: 날짜 상태 변경 요청 시의 동시성 문제 해결
  lodge/build.gradle
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeDateFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeDateServiceImpl.java
  lodge/src/main/java/com/haot/lodge/common/config/RedisConfig.java
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/main/java/com/haot/lodge/common/utils/RedisLockManager.java
  lodge/src/main/java/com/haot/lodge/domain/model/LodgeDate.java
  lodge/src/main/resources/application.yml
  lodge/src/test/java/com/haot/lodge/LodgeDateUpdateStatusTest.java
Labels: fix

#162 [Feat] Reservation: 예약 검색 API 구현
  reservation/build.gradle
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationAdminSearchRequest.java
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationSearchRequest.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/haot/reservation/common/exceptions/ReservationException.java
  reservation/src/main/java/com/haot/reservation/common/exceptions/handler/GlobalExceptionHandler.java
  reservation/src/main/java/com/haot/reservation/common/response/enums/ErrorCode.java
  reservation/src/main/java/com/haot/reservation/domain/repository/ReservationRepository.java
  reservation/src/main/java/com/haot/reservation/domain/utils/QuerydslSortUtils.java
  reservation/src/main/java/com/haot/reservation/infrastructure/config/QueryDslConfig.java
  reservation/src/main/java/com/haot/reservation/infrastructure/config/QueryDslPageableConfig.java
  reservation/src/main/java/com/haot/reservation/infrastructure/config/QueryDslPageableResolver.java
  reservation/src/main/java/com/haot/reservation/infrastructure/repository/ReservationCustomRepository.java
  reservation/src/main/java/com/haot/reservation/infrastructure/repository/ReservationCustomRepositoryImpl.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/AdminReservationController.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/ReservationController.java
Labels: feature

#169 [Refactor] Lodge: 검색 파라미터를 객체로 받도록 변경
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeDateSearchCriteria.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeSearchCriteria.java
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeDateFacade.java
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeDateServiceImpl.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeServiceImpl.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeCustomRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeDateCustomRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/impl/LodgeCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/domain/repository/impl/LodgeDateCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeDateSearchParams.java
  lodge/src/main/java/com/haot/lodge/presentation/request/LodgeSearchParams.java
Labels: refactor

#168 [Refactor] Payment: 코드 리팩토링 및 테스트 코드 추가
  payment/build.gradle
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentCancelRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentCreateRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentSearchRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentUpdateRequest.java
  payment/src/main/java/com/haot/payment/application/dto/response/PageResponse.java
  payment/src/main/java/com/haot/payment/application/dto/response/PaymentResponse.java
  payment/src/main/java/com/haot/payment/application/service/PaymentService.java
  payment/src/main/java/com/haot/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/haot/payment/common/response/ApiResponse.java
  payment/src/main/java/com/haot/payment/domain/utils/QueryDslSortUtils.java
  payment/src/main/java/com/haot/payment/infrastructure/config/QueryDslPageableConfig.java
  payment/src/main/java/com/haot/payment/infrastructure/config/QueryDslPageableResolver.java
  payment/src/main/java/com/haot/payment/infrastructure/config/SwaggerConfig.java
  payment/src/main/java/com/haot/payment/infrastructure/repository/PaymentRepositoryCustomImpl.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
  payment/src/test/java/com/haot/payment/application/service/PaymentServiceImplTest.java
  payment/src/test/java/com/haot/payment/presentation/controller/AdminPaymentControllerTest.java
  payment/src/test/java/com/haot/payment/presentation/controller/PaymentControllerTest.java
Labels: refactor

#172 [Refactor] Lodge: 패키지 구조 개선
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeDateDto.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeDateSearchCriteria.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeDto.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeImageDto.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeRuleDto.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeSearchCriteria.java
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeDateFacade.java
  lodge/src/main/java/com/haot/lodge/application/facade/LodgeFacade.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeCreateResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeDateReadResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeReadAllResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeReadOneResponse.java
  lodge/src/main/java/com/haot/lodge/application/service/LodgeDateService.java
  lodge/src/main/java/com/haot/lodge/application/service/implement/LodgeDateServiceImpl.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeDateRepository.java
  lodge/src/main/java/com/haot/lodge/domain/repository/LodgeRepository.java
  lodge/src/main/java/com/haot/lodge/infrastructure/config/QueryDslConfig.java
  lodge/src/main/java/com/haot/lodge/infrastructure/repository/LodgeCustomRepository.java
  lodge/src/main/java/com/haot/lodge/infrastructure/repository/LodgeDateCustomRepository.java
  lodge/src/main/java/com/haot/lodge/infrastructure/repository/impl/LodgeCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/infrastructure/repository/impl/LodgeDateCustomRepositoryImpl.java
  lodge/src/main/java/com/haot/lodge/infrastructure/utils/QuerydslSortUtils.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodge/LodgeCreateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodge/LodgeSearchParams.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodge/LodgeUpdateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateAddRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateSearchParams.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateUpdateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateUpdateStatusRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeCreateResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeDateReadResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeReadAllResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/response/LodgeReadOneResponse.java
Labels: refactor

#158 [Feat] User: 유저 조회, 업데이트 API 구현 (#157)
  user/src/main/java/com/haot/user/application/dto/req/AdminUserUpdateRequest.java
  user/src/main/java/com/haot/user/application/dto/req/UserUpdateMeRequest.java
  user/src/main/java/com/haot/user/application/dto/res/AdminUserGetResponse.java
  user/src/main/java/com/haot/user/application/dto/res/UserGetMeResponse.java
  user/src/main/java/com/haot/user/application/service/AdminUserCRUDService.java
  user/src/main/java/com/haot/user/application/service/AdminUserCRUDServiceImpl.java
  user/src/main/java/com/haot/user/application/service/UserCRUDService.java
  user/src/main/java/com/haot/user/application/service/UserCRUDServiceImpl.java
  user/src/main/java/com/haot/user/domain/model/User.java
  user/src/main/java/com/haot/user/presentation/controller/AdminUserController.java
  user/src/main/java/com/haot/user/presentation/controller/UserController.java
Labels: feature

#175 [Refactor] Reservation: 예약 생성 리팩토링
  reservation/build.gradle
  reservation/src/main/java/com/haot/reservation/application/dtos/ReservationData.java
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationAdminSearchRequest.java
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationCancelRequest.java
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationCreateRequest.java
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationSearchRequest.java
  reservation/src/main/java/com/haot/reservation/application/dtos/req/ReservationUpdateRequest.java
  reservation/src/main/java/com/haot/reservation/application/dtos/res/ReservationGetResponse.java
  reservation/src/main/java/com/haot/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/haot/reservation/common/exceptions/FeignExceptionUtils.java
  reservation/src/main/java/com/haot/reservation/common/response/ApiResponse.java
  reservation/src/main/java/com/haot/reservation/common/response/enums/ErrorCode.java
  reservation/src/main/java/com/haot/reservation/common/response/enums/SuccessCode.java
  reservation/src/main/java/com/haot/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/coupon/FeignConfirmReservationRequest.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/coupon/FeignVerifyRequest.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/lodge/LodgeDateUpdateStatusRequest.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/payment/PaymentCancelRequest.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/payment/PaymentCreateRequest.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/point/PointStatusRequest.java
  reservation/src/main/java/com/haot/reservation/infrastructure/dtos/point/PointTransactionRequest.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/AdminReservationController.java
  reservation/src/main/java/com/haot/reservation/presentation/controller/ReservationController.java
Labels: refactor

#178 [Docs] Lodge: API 스웨거 문서화
  lodge/build.gradle
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeDateDto.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeDto.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeImageDto.java
  lodge/src/main/java/com/haot/lodge/application/dto/LodgeRuleDto.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeCreateResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeDateReadResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeReadAllResponse.java
  lodge/src/main/java/com/haot/lodge/application/response/LodgeReadOneResponse.java
  lodge/src/main/java/com/haot/lodge/common/config/SwaggerConfig.java
  lodge/src/main/java/com/haot/lodge/common/response/SliceResponse.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeController.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeControllerDocs.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateController.java
  lodge/src/main/java/com/haot/lodge/presentation/controller/LodgeDateControllerDocs.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodge/LodgeCreateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodge/LodgeSearchParams.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodge/LodgeUpdateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateAddRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateSearchParams.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateUpdateRequest.java
  lodge/src/main/java/com/haot/lodge/presentation/request/lodgedate/LodgeDateUpdateStatusRequest.java
Labels: documentation

#182 [Refactor] Review: swagger, testcode, s3
  review/build.gradle
  review/src/main/java/com/haot/review/application/dtos/req/ReviewCreateRequest.java
  review/src/main/java/com/haot/review/application/dtos/req/ReviewSearchRequest.java
  review/src/main/java/com/haot/review/application/dtos/req/ReviewUpdateRequest.java
  review/src/main/java/com/haot/review/application/dtos/res/ReviewGetResponse.java
  review/src/main/java/com/haot/review/application/service/MockS3Service.java
  review/src/main/java/com/haot/review/application/service/ReviewService.java
  review/src/main/java/com/haot/review/application/service/ReviewServiceImpl.java
  review/src/main/java/com/haot/review/application/service/S3Service.java
  review/src/main/java/com/haot/review/common/response/enums/ErrorCode.java
  review/src/main/java/com/haot/review/domain/model/Review.java
  review/src/main/java/com/haot/review/domain/model/ReviewImage.java
  review/src/main/java/com/haot/review/infrastructure/configuration/QueryDslPageableConfig.java
  review/src/main/java/com/haot/review/infrastructure/configuration/QueryDslPageableResolver.java
  review/src/main/java/com/haot/review/infrastructure/configuration/S3Config.java
  review/src/main/java/com/haot/review/infrastructure/repository/ReviewRepositoryCustom.java
  review/src/main/java/com/haot/review/infrastructure/repository/ReviewRepositoryCustomImpl.java
  review/src/main/java/com/haot/review/infrastructure/utils/QuerydslSortUtils.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewController.java
  review/src/main/resources/application.yml
  review/src/test/java/com/haot/review/application/TestMockData.java
  review/src/test/java/com/haot/review/application/service/ReviewServiceImplTest.java
Labels: documentation, refactor, test

#177 [Refactor] Point: Pageable 리팩토링 및 조회에 Redis 적용
  point/build.gradle
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/UserPointHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/dto/response/PageResponse.java
  point/src/main/java/com/haot/point/application/dto/response/PointHistoryResponse.java
  point/src/main/java/com/haot/point/application/dto/response/PointResponse.java
  point/src/main/java/com/haot/point/application/service/PointHistoryService.java
  point/src/main/java/com/haot/point/application/service/PointHistoryServiceImpl.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/domain/utils/CacheEvictUtils.java
  point/src/main/java/com/haot/point/domain/utils/QueryDslSortUtils.java
  point/src/main/java/com/haot/point/infrastructure/config/CacheConfig.java
  point/src/main/java/com/haot/point/infrastructure/config/QueryDslPageableConfig.java
  point/src/main/java/com/haot/point/infrastructure/config/QueryDslPageableResolver.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepository.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepositoryCustomImpl.java
  point/src/main/java/com/haot/point/infrastructure/serializer/PageResponseSerializer.java
  point/src/main/java/com/haot/point/presentation/controller/PointHistoryController.java
  point/src/main/resources/application.yml
Labels: feature, refactor

#180 [Refactor] Gateway 및 User 서비스에 Redis 적용
  gateway/build.gradle
  gateway/src/main/java/com/haot/gateway/filter/JwtAuthenticationFilter.java
  gateway/src/main/resources/application.yml
  user/build.gradle
  user/src/main/java/com/haot/user/application/service/UserCRUDServiceImpl.java
  user/src/main/java/com/haot/user/application/service/UserValidationServiceImpl.java
  user/src/main/java/com/haot/user/common/config/CacheConfig.java
  user/src/main/resources/application.yml
Labels: feature

#190 [Test] Lodge: Facade 테스트 코드 추가
  lodge/src/main/java/com/haot/lodge/common/exception/ErrorCode.java
  lodge/src/test/java/com/haot/lodge/lodge/controller/LodgeControllerCreatTest.java
  lodge/src/test/java/com/haot/lodge/lodge/controller/LodgeControllerReadAllTest.java
  lodge/src/test/java/com/haot/lodge/lodge/controller/LodgeControllerReadOneTest.java
  lodge/src/test/java/com/haot/lodge/lodge/facade/LodgeFacadeCreateTest.java
  lodge/src/test/java/com/haot/lodge/lodge/facade/LodgeFacadeDeleteTest.java
  lodge/src/test/java/com/haot/lodge/lodge/facade/LodgeFacadeReadAllTest.java
  lodge/src/test/java/com/haot/lodge/lodge/facade/LodgeFacadeReadTest.java
  lodge/src/test/java/com/haot/lodge/lodge/facade/LodgeFacadeUpdateTest.java
  lodge/src/test/java/com/haot/lodge/lodgedate/facade/LodgeDateFacadeAddTest.java
  lodge/src/test/java/com/haot/lodge/lodgedate/facade/LodgeDateFacadeReadTest.java
  lodge/src/test/java/com/haot/lodge/lodgedate/facade/LodgeDateUpdateStatusTest.java
  lodge/src/test/java/com/haot/lodge/lodgedate/service/LodgeDateServiceCreateTest.java
  lodge/src/test/java/com/haot/lodge/util/TestDtoFixture.java
  lodge/src/test/java/com/haot/lodge/util/TestEntityFixture.java
Labels: test

#191 [Refactor] Point: 코드 리팩토링 및 스웨거 추가
  point/build.gradle
  point/src/main/java/com/haot/point/application/dto/request/PointTransactionRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistoryCreateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistoryUpdateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/UserPointHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/dto/request/point/PointCreateRequest.java
  point/src/main/java/com/haot/point/application/dto/request/point/PointStatusRequest.java
  point/src/main/java/com/haot/point/application/dto/request/point/PointUpdateRequest.java
  point/src/main/java/com/haot/point/application/dto/response/PageResponse.java
  point/src/main/java/com/haot/point/application/dto/response/PointAllResponse.java
  point/src/main/java/com/haot/point/application/dto/response/PointHistoryResponse.java
  point/src/main/java/com/haot/point/application/dto/response/PointResponse.java
  point/src/main/java/com/haot/point/application/service/PointHistoryServiceImpl.java
  point/src/main/java/com/haot/point/application/service/PointServiceImpl.java
  point/src/main/java/com/haot/point/infrastructure/config/SwaggerConfig.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointController.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointHistoryController.java
  point/src/main/java/com/haot/point/presentation/controller/PointController.java
  point/src/main/java/com/haot/point/presentation/controller/PointHistoryController.java
  point/src/main/java/com/haot/point/presentation/docs/AdminPointControllerDocs.java
  point/src/main/java/com/haot/point/presentation/docs/AdminPointHistoryControllerDocs.java
  point/src/main/java/com/haot/point/presentation/docs/PointControllerDocs.java
  point/src/main/java/com/haot/point/presentation/docs/PointHistoryControllerDocs.java
  point/src/main/resources/application.yml
  point/src/main/resources/logback.xml
Labels: refactor

#193 [Refactor] Payment: 스웨거 설정 변경 맟 모니터링 설정 추가
  payment/build.gradle
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentCancelRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentCreateRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentSearchRequest.java
  payment/src/main/java/com/haot/payment/application/dto/request/PaymentUpdateRequest.java
  payment/src/main/java/com/haot/payment/application/dto/response/PageResponse.java
  payment/src/main/java/com/haot/payment/application/dto/response/PaymentResponse.java
  payment/src/main/java/com/haot/payment/infrastructure/config/SwaggerConfig.java
  payment/src/main/java/com/haot/payment/presentation/controller/AdminPaymentController.java
  payment/src/main/java/com/haot/payment/presentation/controller/PaymentController.java
  payment/src/main/java/com/haot/payment/presentation/docs/AdminPaymentControllerDocs.java
  payment/src/main/java/com/haot/payment/presentation/docs/PaymentControllerDocs.java
  payment/src/main/resources/application.yml
  payment/src/main/resources/logback.xml
Labels: refactor

#194 [CICD] application-prod.yml 추가 및 cicd.yml 수정
  .github/workflows/cicd.yml
  auth/src/main/resources/application-prod.yml
  coupon/src/main/resources/application-prod.yml
  gateway/src/main/resources/application-prod.yml
  lodge/src/main/resources/application-prod.yml
  payment/src/main/resources/application-prod.yml
  point/src/main/resources/application-prod.yml
  reservation/src/main/resources/application-prod.yml
  review/src/main/resources/application-prod.yml
  server/src/main/resources/application-prod.yml
  user/src/main/resources/application-prod.yml
Labels: feature

#195 [Docs] Lodge: 스웨거 설정 컨벤션 맞게 수정
  lodge/build.gradle
  lodge/src/main/java/com/haot/lodge/common/config/SwaggerConfig.java
Labels: documentation, fix

#204 [Test] Point: 테스트 코드 수정
  point/src/main/java/com/haot/point/infrastructure/config/CacheConfig.java
  point/src/test/java/com/haot/point/presentation/controller/PointControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/PointHistoryControllerTest.java
Labels: fix, test

#206 Refactor: 예약, 리뷰 리팩토링
  reservation/src/main/java/com/haot/reservation/common/response/enums/ErrorCode.java
  reservation/src/main/java/com/haot/reservation/common/response/enums/SuccessCode.java
  review/src/main/java/com/haot/review/application/service/ReviewServiceImpl.java
  review/src/main/java/com/haot/review/common/response/enums/ErrorCode.java
  review/src/main/java/com/haot/review/common/response/enums/SuccessCode.java
  review/src/main/java/com/haot/review/infrastructure/client/LodgeClient.java
  review/src/main/java/com/haot/review/infrastructure/dto/LodgeImageResponse.java
  review/src/main/java/com/haot/review/infrastructure/dto/LodgeReadOneResponse.java
  review/src/main/java/com/haot/review/infrastructure/dto/LodgeResponse.java
  review/src/main/java/com/haot/review/infrastructure/dto/LodgeRuleResponse.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewController.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewControllerDocs.java
  review/src/test/java/com/haot/review/application/service/ReviewServiceImplTest.java
Labels: refactor, fix

#209 [Refactor] Point: Admin 코드로 분리
  payment/src/main/java/com/haot/payment/common/exception/handler/GlobalExceptionHandler.java
  point/src/main/java/com/haot/point/application/dto/request/history/AdminHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/PointHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/dto/request/history/UserPointHistorySearchRequest.java
  point/src/main/java/com/haot/point/application/service/AdminPointHistoryService.java
  point/src/main/java/com/haot/point/application/service/PointHistoryService.java
  point/src/main/java/com/haot/point/application/service/PointService.java
  point/src/main/java/com/haot/point/application/service/impl/AdminPointHistoryServiceImpl.java
  point/src/main/java/com/haot/point/application/service/impl/PointHistoryServiceImpl.java
  point/src/main/java/com/haot/point/application/service/impl/PointServiceImpl.java
  point/src/main/java/com/haot/point/common/exception/handler/GlobalExceptionHandler.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepositoryCustom.java
  point/src/main/java/com/haot/point/infrastructure/repository/PointHistoryRepositoryCustomImpl.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointController.java
  point/src/main/java/com/haot/point/presentation/controller/AdminPointHistoryController.java
  point/src/main/java/com/haot/point/presentation/controller/PointController.java
  point/src/main/java/com/haot/point/presentation/controller/PointHistoryController.java
  point/src/main/java/com/haot/point/presentation/docs/AdminPointHistoryControllerDocs.java
  point/src/main/java/com/haot/point/presentation/docs/PointHistoryControllerDocs.java
  point/src/test/java/com/haot/point/presentation/controller/AdminPointHistoryControllerTest.java
  point/src/test/java/com/haot/point/presentation/controller/PointHistoryControllerTest.java
  review/src/main/java/com/haot/review/presentation/controller/ReviewController.java
  review/src/main/java/com/haot/review/presentation/docs/ReviewControllerDocs.java
Labels: refactor

#197 [Fix] cicd.yml 에서 오타 수정 및 Port one sed 명령어 안되던 버그 수정
  .github/workflows/cicd.yml
  auth/Dockerfile
  auth/src/main/java/com/haot/auth/common/config/SwaggerConfig.java
  auth/src/main/resources/application-prod.yml
  auth/src/main/resources/logback.xml
  coupon/Dockerfile
  coupon/src/main/java/com/haot/coupon/infrastructure/config/SwaggerConfig.java
  coupon/src/main/resources/application-prod.yml
  coupon/src/main/resources/logback.xml
  gateway/Dockerfile
  gateway/src/main/java/com/haot/gateway/client/UserWebClient.java
  gateway/src/main/java/com/haot/gateway/filter/JwtAuthenticationFilter.java
  gateway/src/main/resources/logback.xml
  lodge/Dockerfile
  lodge/src/main/java/com/haot/lodge/common/config/RedisConfig.java
  lodge/src/main/java/com/haot/lodge/common/config/SwaggerConfig.java
  lodge/src/main/resources/application-prod.yml
  lodge/src/main/resources/logback.xml
  payment/Dockerfile
  payment/src/main/java/com/haot/payment/infrastructure/config/SwaggerConfig.java
  payment/src/main/resources/application-prod.yml
  payment/src/main/resources/logback.xml
  point/Dockerfile
  point/src/main/java/com/haot/point/infrastructure/config/SwaggerConfig.java
  point/src/main/resources/application-prod.yml
  point/src/main/resources/logback.xml
  reservation/Dockerfile
  reservation/src/main/java/com/haot/reservation/infrastructure/config/SwaggerConfig.java
  reservation/src/main/resources/application-prod.yml
  reservation/src/main/resources/logback.xml
  review/Dockerfile
  review/src/main/java/com/haot/review/infrastructure/configuration/SwaggerConfig.java
  review/src/main/resources/application-prod.yml
  review/src/main/resources/logback.xml
  server/Dockerfile
  user/Dockerfile
  user/src/main/java/com/haot/user/common/config/SwaggerConfig.java
  user/src/main/resources/application-prod.yml
  user/src/main/resources/logback.xml
Labels: fix

#208 [Docs] README 추가
  README.md
Labels: documentation
